# Generated by Django 4.0.6 on 2023-07-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='angkatan',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lulusan',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='logounpad.jpg', upload_to='photo'),
        ),
    ]
