# Generated by Django 4.0.6 on 2023-07-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_buku_event_loker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='foto',
            field=models.ImageField(upload_to='event'),
        ),
    ]
