# Generated by Django 4.0.6 on 2023-07-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_alter_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loker',
            name='batas',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='foto',
            field=models.ImageField(blank=True, upload_to='event'),
        ),
    ]
