# Generated by Django 4.0.6 on 2023-07-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0010_loker_batas_alter_event_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('view_mypage', 'Can view My Page')]},
        ),
    ]
