# Generated by Django 4.0.6 on 2023-07-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0014_survei_jabatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('judul', models.CharField(max_length=150)),
                ('artikel', models.TextField()),
            ],
        ),
    ]
